### ISSUE TITLE
Not finding file on S3 bucket

### ISSUE THREAD

**Issue by mshodge** [moj-analytical-services/mojap-arrow-pd-parser#96]
Using version `1.3.7` getting the following error on a DAG Airflow:

```
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO - Traceback (most recent call last):
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "python_scripts/sop_land_to_raw_hist.py", line 163, in <module>
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -     writer.write(df=df, output_path=reformat_path)
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "/usr/local/lib/python3.8/site-packages/arrow_pd_parser/writer.py", line 46, in write
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -     return writer.write(
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "/usr/local/lib/python3.8/site-packages/arrow_pd_parser/_writers.py", line 290, in write
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -     self._write(df, output_path, arrow_schema, **kwargs)
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "/usr/local/lib/python3.8/site-packages/arrow_pd_parser/_writers.py", line 328, in _write
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -     written_arrow_schema = pq.read_schema(output_path)
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "/usr/local/lib/python3.8/site-packages/pyarrow/parquet.py", line 2299, in read_schema
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -     return ParquetFile(where, memory_map=memory_map).schema.to_arrow_schema()
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "/usr/local/lib/python3.8/site-packages/pyarrow/parquet.py", line 230, in __init__
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -     self.reader.open(
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "pyarrow/_parquet.pyx", line 970, in pyarrow._parquet.ParquetReader.open
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "pyarrow/io.pxi", line 1611, in pyarrow.lib.get_reader
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "pyarrow/io.pxi", line 1602, in pyarrow.lib.get_native_file
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile.__cinit__
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "pyarrow/io.pxi", line 906, in pyarrow.lib.OSFile._open_readable
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO -   File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
[2023-05-12, 15:30:12 UTC] {{pod_manager.py:228}} INFO - FileNotFoundError: [Errno 2] Failed to open local file 's3://alpha-contracts-etl/v1/sop/raw-hist/pass/sop_transactional/ApExtractMar23_1683905239-1-1683905239.snappy.parquet'. Detail: [errno 2] No such file or directory
```

The file does exist though.

Speaking to others it seems using a roll-backed version works, but this indicates a fix is required for the latest version.

**Comment by Thomas-Hirsch** [comment]
This error was indeed introduced in v1.3.4. The issue is that [`pyarrow.parquet.read_schema()`](https://github.com/moj-analytical-services/mojap-arrow-pd-parser/blob/main/arrow_pd_parser/_writers.py#L328) doesn't work with S3 paths, so that's why it would never work. What it should be doing is write to a local path, test the locally written file's schema against the provided schema, and then write to S3

**Comment by gwionap** [comment]
Where does it use `read_schema` @Thomas-Hirsch - if you point me to it, I know how to adapt it to read from S3

**Comment by mshodge** [comment]
Similar to https://github.com/moj-analytical-services/data_linter/pull/194
